# Generated by Django 2.1.1 on 2018-09-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swethasblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
